import type { Metadata } from "next";
import "@/css/global.css";
import { josefin, raleway, sourceSans } from "@/fonts/main";
import { Navigation } from "@/layout/navigation";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pl-PL">
      <body
        className={`${sourceSans.variable} ${josefin.variable} ${raleway.variable} antialiased`}
      >
        <Navigation
           isArticle
        />
        {children}
      </body>
    </html>
  );
}
